/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.jwinapp;
import clsrestapi.AboutUs;
import clsrestapi.ContactInfo;
import clsrestapi.OurWork;
import clsrestapi.ShowCaseVideo;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.net.URL;
import java.util.ListIterator;


/**
 *
 * @author Ken Lowrie
 */
public class jWinAppUI extends javax.swing.JFrame {

    private AboutUs aboutUs;
    private ContactInfo contactInfo;
    private OurWork ourWork;

    private void logMsg(String msg){
        System.out.println(msg);
    }
    /**
     * Creates new form jWinAppUI
     */
    public jWinAppUI() {
        initComponents();
        loadAbout();
        loadContact();
        loadOurWork();
    }
    
    private void loadAbout(){
        aboutUs = new AboutUs().load();
        
        jTextAreaAbout.append(aboutUs.apiObj.aboutus.replace(". ", "." + System.lineSeparator() + System.lineSeparator()));
        
    }
    
    private void loadContact(){
        contactInfo = new ContactInfo().load();
        
        StringBuilder sb = new StringBuilder();
        
        sb.append(contactInfo.apiObj.location);
        sb.append(System.lineSeparator()).append(System.lineSeparator());
        sb.append(contactInfo.apiObj.address.getMailingAddress());
        sb.append(System.lineSeparator());
        sb.append("Email: ").append(contactInfo.apiObj.email).append(System.lineSeparator());
        sb.append("Phone: ").append(contactInfo.apiObj.phone);
        
        jTextAreaContact.append(sb.toString());        
    }

    private void loadOurWork(){
        ourWork = new OurWork().load();
        
        Object columnNames[] = { "Thumbnail", "Description" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for(ListIterator<ShowCaseVideo> iter = ourWork.apiObj.videoList.listIterator(); iter.hasNext();){
            ShowCaseVideo video = iter.next();
            Object rowData[] = {"", "<html><strong>" + video.type + "</strong><br>" + video.title};
            
            model.addRow(rowData);
        }
        jTableOurWork.setModel(model);
        jTableOurWork.setRowHeight(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabelCloudyLogic = new javax.swing.JLabel();
        jLabelGitHub = new javax.swing.JLabel();
        jLabelRefApp = new javax.swing.JLabel();
        jLabelFB = new javax.swing.JLabel();
        jLabelTwitter = new javax.swing.JLabel();
        jLabelInstagram = new javax.swing.JLabel();
        jLabelVimeo = new javax.swing.JLabel();
        jPanelOurWork = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOurWork = new javax.swing.JTable();
        jPanelAboutUs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAbout = new javax.swing.JTextArea();
        jPanelContact = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaContact = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jLabelCloudyLogic.setText("<html><a href=\"https://cloudylogic.com\">Cloudy Logic Studios, LLC</a>.");
        jLabelCloudyLogic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openCloudyLogic(evt);
            }
        });

        jLabelGitHub.setText("<html><a href=\"https://github.com/kenlowrie/jwinapp\">github.com/kenlowrie/jWinApp</a>");
        jLabelGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openGitHub(evt);
            }
        });

        jLabelRefApp.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelRefApp.setText("Java Reference App");

        jLabelFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/jwinapp/social-fb3@2x.png"))); // NOI18N
        jLabelFB.setText("Facebook");
        jLabelFB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelFB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openFB(evt);
            }
        });

        jLabelTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/jwinapp/social-tw3@2x.png"))); // NOI18N
        jLabelTwitter.setText("Twitter");
        jLabelTwitter.setMaximumSize(new java.awt.Dimension(128, 162));
        jLabelTwitter.setMinimumSize(new java.awt.Dimension(128, 162));
        jLabelTwitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openTwitter(evt);
            }
        });

        jLabelInstagram.setText("Instagram");
        jLabelInstagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openInstagram(evt);
            }
        });

        jLabelVimeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/jwinapp/social-vi3@2x.png"))); // NOI18N
        jLabelVimeo.setText("Vimeo");
        jLabelVimeo.setMaximumSize(new java.awt.Dimension(110, 162));
        jLabelVimeo.setMinimumSize(new java.awt.Dimension(110, 162));
        jLabelVimeo.setPreferredSize(new java.awt.Dimension(128, 169));
        jLabelVimeo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openVimeo(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabelFB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVimeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabelCloudyLogic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelRefApp)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGitHub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInstagram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTwitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVimeo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCloudyLogic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGitHub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRefApp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanelHome);

        jTableOurWork.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTableOurWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOurWork.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableOurWork);
        if (jTableOurWork.getColumnModel().getColumnCount() > 0) {
            jTableOurWork.getColumnModel().getColumn(0).setResizable(false);
            jTableOurWork.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanelOurWorkLayout = new javax.swing.GroupLayout(jPanelOurWork);
        jPanelOurWork.setLayout(jPanelOurWorkLayout);
        jPanelOurWorkLayout.setHorizontalGroup(
            jPanelOurWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOurWorkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelOurWorkLayout.setVerticalGroup(
            jPanelOurWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOurWorkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Our Work", jPanelOurWork);

        jPanelAboutUs.setBorder(javax.swing.BorderFactory.createTitledBorder("AboutUs"));

        jTextAreaAbout.setColumns(20);
        jTextAreaAbout.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextAreaAbout.setLineWrap(true);
        jTextAreaAbout.setRows(5);
        jTextAreaAbout.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaAbout);

        javax.swing.GroupLayout jPanelAboutUsLayout = new javax.swing.GroupLayout(jPanelAboutUs);
        jPanelAboutUs.setLayout(jPanelAboutUsLayout);
        jPanelAboutUsLayout.setHorizontalGroup(
            jPanelAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelAboutUsLayout.setVerticalGroup(
            jPanelAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("About Us", jPanelAboutUs);
        jPanelAboutUs.getAccessibleContext().setAccessibleName("");

        jTextAreaContact.setColumns(20);
        jTextAreaContact.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextAreaContact.setRows(5);
        jScrollPane3.setViewportView(jTextAreaContact);

        jLabel2.setText("Put a Google map in this area, when you click it launch a big version");

        javax.swing.GroupLayout jPanelContactLayout = new javax.swing.GroupLayout(jPanelContact);
        jPanelContact.setLayout(jPanelContactLayout);
        jPanelContactLayout.setHorizontalGroup(
            jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactLayout.createSequentialGroup()
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContactLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                    .addGroup(jPanelContactLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelContactLayout.setVerticalGroup(
            jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContactLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contact", jPanelContact);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openURL(String url){
        try {
           Desktop.getDesktop().browse(new URL(url).toURI());            
        } catch( Exception E){
            // TODO: Log an error to a log of some sort or do a popup...
        }
        
    }
    
    private void browseSocialNetwork(String network){
        if( contactInfo.dbgObj.parseOK){
            String snUrl = contactInfo.apiObj.getSocialNetworkUrl(network);
                        
            if( snUrl != null ){
                openURL(snUrl);
            } 
        }       
    }
    
    private void openFB(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openFB
        // TODO add your handling code here:
        browseSocialNetwork("Facebook");
    }//GEN-LAST:event_openFB

    private void openTwitter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openTwitter
        // TODO add your handling code here:
        browseSocialNetwork("Twitter");        
    }//GEN-LAST:event_openTwitter

    private void openInstagram(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openInstagram
        // TODO add your handling code here:
        browseSocialNetwork("Instagram");        
    }//GEN-LAST:event_openInstagram

    private void openVimeo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openVimeo
        // TODO add your handling code here:
        browseSocialNetwork("Vimeo");        
    }//GEN-LAST:event_openVimeo

    private void openCloudyLogic(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openCloudyLogic
        // TODO add your handling code here:
        openURL("https://cloudylogic.com");
    }//GEN-LAST:event_openCloudyLogic

    private void openGitHub(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openGitHub
        // TODO add your handling code here:
        openURL("https://github.com/kenlowrie/jWinApp");
    }//GEN-LAST:event_openGitHub

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jWinAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jWinAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jWinAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jWinAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jWinAppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCloudyLogic;
    private javax.swing.JLabel jLabelFB;
    private javax.swing.JLabel jLabelGitHub;
    private javax.swing.JLabel jLabelInstagram;
    private javax.swing.JLabel jLabelRefApp;
    private javax.swing.JLabel jLabelTwitter;
    private javax.swing.JLabel jLabelVimeo;
    private javax.swing.JPanel jPanelAboutUs;
    private javax.swing.JPanel jPanelContact;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelOurWork;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableOurWork;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextAreaAbout;
    private javax.swing.JTextArea jTextAreaContact;
    // End of variables declaration//GEN-END:variables
}
